apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: bangjeff-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: do-regcred
      containers:
        - name: user-service
          image: registry.digitalocean.com/bangjeff/user-service:latest
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: root-app-mitra--env-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: bangjeff-dev
spec:
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 9090
  type: ClusterIP
