apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: bangjeff-dev
  labels:
    app: core-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      imagePullSecrets:
        - name: do-regcred
      containers:
        - name: core-service
          image: registry.digitalocean.com/bangjeff/core-service:latest
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: bangjeff-env-service
            - secretRef:
                name: root-app-bangjeff--secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /v3/health
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /v3/health
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: bangjeff-dev
spec:
  selector:
    app: core-service
  ports:
    - port: 80
      targetPort: 9090
  type: ClusterIP
